### ISSUE TITLE
Can't get the app launched, even with the examples

### ISSUE THREAD

**Issue by mrgoonie** [saltyshiomix/nextron#135]
I tried to install Nextron and started with the examples, but I can't get any of them to work.

The error showed up after `yarn && yarn dev` is:

```
$ nextron
ready - started server on http://localhost:8888
Warning: Built-in CSS support is being disabled due to custom CSS configuration being detected.
See here for more info: https://err.sh/next.js/built-in-css-disabled

event - compiled successfully
Debugger listening on ws://127.0.0.1:9292/98887472-74b3-47a2-92fd-b05ac448bd9a
For help, see: https://nodejs.org/en/docs/inspector
App threw an error during load
Error: Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module '@babel/plugin-proposal-class-properties' from '/Users/duynguyen/www/nextron-ant-app'
    at Function.resolveSync [as sync] (/Users/duynguyen/www/nextron-ant-app/node_modules/resolve/lib/sync.js:90:15)
    at resolveStandardizedName (/Users/duynguyen/www/nextron-ant-app/node_modules/@babel/core/lib/config/files/plugins.js:101:31)
    at resolvePlugin (/Users/duynguyen/www/nextron-ant-app/node_modules/@babel/core/lib/config/files/plugins.js:54:10)
    at loadPlugin (/Users/duynguyen/www/nextron-ant-app/node_modules/@babel/core/lib/config/files/plugins.js:62:20)
    at createDescriptor (/Users/duynguyen/www/nextron-ant-app/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
    at /Users/duynguyen/www/nextron-ant-app/node_modules/@babel/core/lib/config/config-descriptors.js:109:50
    at Array.map (<anonymous>)
    at createDescriptors (/Users/duynguyen/www/nextron-ant-app/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPluginDescriptors (/Users/duynguyen/www/nextron-ant-app/node_modules/@babel/core/lib/config/config-descriptors.js:105:10)
    at /Users/duynguyen/www/nextron-ant-app/node_modules/@babel/core/lib/config/config-descriptors.js:63:53
    at Object../main/background.js (/Users/duynguyen/www/nextron-ant-app/app/background.js:97:7)
    at __webpack_require__ (/Users/duynguyen/www/nextron-ant-app/app/background.js:21:30)
    at /Users/duynguyen/www/nextron-ant-app/app/background.js:85:18
    at Object.<anonymous> (/Users/duynguyen/www/nextron-ant-app/app/background.js:88:10)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12694)
    at loadApplicationPackage (/Users/duynguyen/www/nextron-ant-app/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:110:16)
```

![image](https://user-images.githubusercontent.com/6857382/100520119-c13daa00-31ce-11eb-9304-168b3deba270.png)

Any ideas why? :D

**Comment by Psycokwet** [comment]
Same issue as here : https://github.com/saltyshiomix/nextron/issues/134

I've come with a fix, but I'm still waiting on @saltyshiomix  opinion on this. I don't think we need two issues for the same issue, if you agree with me, you can close this one ^^

Don't hesitate to tell me if my fix works for you :)

**Comment by mrgoonie** [comment]
You're right, installing those packages would help! #134
