### ISSUE TITLE
Can't use TypeScript enums by default?

### ISSUE THREAD

**Issue by luker2** [saltyshiomix/nextron#153]
Hi! I'm using example `with-typescript-tailwindcss`. 

I'm trying to share an enum between `main` & `renderer` so I can create strong typings between node.js & the browser for `ipc`.

`my-app/renderer/shared/ipc/types.ts`:
```
export enum NODE_COMMAND {
    SYS_CURRENT_USER = 'SYS_CURRENT_USER',
    SYS_GET_PLATFORM = 'SYS_GET_PLATFORM',
}
```

`yarn dev`:
```
Debugger listening on ws://127.0.0.1:9292/07da729d-9bca-4303-8692-07f8e5f57164
For help, see: https://nodejs.org/en/docs/inspector
App threw an error during load
Error: Module parse failed: Unexpected token (1:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> export enum NODE_COMMAND {
|     SYS_CURRENT_USER = 'SYS_CURRENT_USER',
|     SYS_GET_PLATFORM = 'SYS_GET_PLATFORM',
    at Object../renderer/shared/ipc/types.ts (C:\git\my-app\app\background.js:9125:7)
    at __webpack_require__ (C:\git\my-app\app\webpack:\webpack\bootstrap:19:1)
    at Module../main/node-service-handlers/system.call.ts (C:\git\my-app\app\background.js:344:84)
    at __webpack_require__ (C:\git\my-app\app\webpack:\webpack\bootstrap:19:1)
    at Module../main/node-service-handlers/index.ts (C:\git\my-app\app\webpack:\main\node-service-handlers\index.ts:1:1)
    at __webpack_require__ (C:\git\my-app\app\webpack:\webpack\bootstrap:19:1)
    at Module../main/background.ts (C:\git\my-app\app\webpack:\main\background.ts:1:1)
    at __webpack_require__ (C:\git\my-app\app\webpack:\webpack\bootstrap:19:1)
    at C:\git\my-app\app\webpack:\webpack\bootstrap:83:1
    at Object.<anonymous> (C:\git\my-app\app\background.js:88:10)

DevTools listening on ws://127.0.0.1:5858/devtools/browser/822a8c25-c124-4e39-a83d-ebdc58a24bc2
```

**Comment by luker2** [comment]
This problem of sharing modules and/or using a monorepo seem similar to #132 and #89

**Comment by tanishqkancharla** [comment]
Hello, did you resolve this issue?
