### ISSUE TITLE
Integration with Electron Store

### ISSUE THREAD

**Issue by ColeTownsend** [saltyshiomix/nextron#16]
Currently when adding `electron-store` to any example (both typescript and js) the loaded page has an internal server error caused by a TypeError.

I've encountered similar issues when building the app using `electron-next`. I'm going to research this as well to see how to make sure Next can see the electron app.

```
TypeError: Cannot read property 'app' of undefined
    at new ElectronStore (/Users/coletownsend/Documents/gits/captcha/node_modules/electron-store/index.js:8:55)
    at Module../pages/_app.jsx (/Users/coletownsend/Documents/gits/captcha/renderer/.next/server/static/development/pages/_app.js:337:21)
    at __webpack_require__ (/Users/coletownsend/Documents/gits/captcha/renderer/.next/server/static/development/pages/_app.js:23:31)
    at Object.0 (/Users/coletownsend/Documents/gits/captcha/renderer/.next/server/static/development/pages/_app.js:886:18)
    at __webpack_require__ (/Users/coletownsend/Documents/gits/captcha/renderer/.next/server/static/development/pages/_app.js:23:31)
    at /Users/coletownsend/Documents/gits/captcha/renderer/.next/server/static/development/pages/_app.js:91:18
    at Object.<anonymous> (/Users/coletownsend/Documents/gits/captcha/renderer/.next/server/static/development/pages/_app.js:94:10)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at _callee3$ (/Users/coletownsend/Documents/gits/captcha/node_modules/next/dist/server/render.js:225:40)
    at tryCatch (/Users/coletownsend/Documents/gits/captcha/node_modules/regenerator-runtime/runtime.js:62:40)
```

**Comment by saltyshiomix** [comment]
@ColeTownsend

This is a `next`'s webpack processes issue.
Next.js runs both server and client build process, so when server build process these errors occur.

See my ipcRenderer process example to tackle them:

https://github.com/saltyshiomix/nextron/blob/master/examples/_template/ts/renderer/helpers/resolveWithIpc.ts

When server build process, ipcRenderer is undefined, and when client one, we can use ipcRenderer as usually.

I hope it helped :)

**Comment by saltyshiomix** [comment]
@ColeTownsend 

I added an `electron-store` example named `store-data` 👍 

https://github.com/saltyshiomix/nextron/tree/master/examples/store-data

You can use it by these instructions:

```bash
# update nextron
$ npm install --global nextron@latest

# use it
$ nextron init my-app --template store-data
$ cd my-app

# development mode
$ yarn dev

# production build
$ yarn build
```

**Comment by ColeTownsend** [comment]
The IPC way works great! Thank you!

**Comment by saltyshiomix** [comment]
@ColeTownsend 

You're welcome :)
@sindresorhus 's `electron-store` (and other tools) are soooo awesome.
