### ISSUE TITLE
Failing to Create a Nextron + Tailwind app

### ISSUE THREAD

**Issue by LincCodes** [saltyshiomix/nextron#172]
```
events.js:292
      throw er; // Unhandled 'error' event
      ^

ReadError: The server aborted pending request
    at IncomingMessage.<anonymous> (C:\Users\-\AppData\Roaming\npm-cache\_npx\9480\node_modules\create-nextron-app\node_modules\got\dist\source\core\index.js:803:31)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:315:20)
    at IncomingMessage.origin.emit (C:\Users\-\AppData\Roaming\npm-cache\_npx\9480\node_modules\create-nextron-app\node_modules\@szmarczak\http-timer\dist\source\index.js:39:20)
    at TLSSocket.socketCloseListener (_http_client.js:426:11)
    at TLSSocket.emit (events.js:327:22)
    at net.js:673:12
    at TCP.done (_tls_wrap.js:563:7)
Emitted 'error' event on Request instance at:
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'ECONNRESET',
  timings: {
    start: 1618050858856,
    socket: 1618050858865,
    lookup: 1618050858902,
    connect: 1618050859128,
    secureConnect: 1618050859387,
    upload: 1618050859388,
    response: 1618050860079,
    end: undefined,
    error: undefined,
    abort: 1618050910856,
    phases: {
      wait: 9,
      dns: 37,
      tcp: 226,
      tls: 259,
      request: 1,
      firstByte: 691,
      download: undefined,
      total: 52000
    }
  }
}
```

The error I am getting, please help fix it.

**Comment by LincCodes** [comment]
```
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm ERR! cb() never called!
```
Errors when I run `npm install`

**Comment by Rashmi-278** [comment]
is tailwind incompatible with electron ? I seem to think I read that somewhere

**Comment by Psycokwet** [comment]
Did you try yarn? Npm has some issues with all template that I tried from nextron

**Comment by TimotiusAnrez** [comment]
my app run perfectly fine, but it fails on build time. Tho there is a problem while installing tailwind, you have to put the tailwind.config.js in root folder not renderer folder.

**Comment by TimotiusAnrez** [comment]
![image](https://user-images.githubusercontent.com/71978054/157847878-9c68d763-dcd0-4b66-ba65-1355995505a5.png)

for more clear idea of the project structure

**Comment by saltyshiomix** [comment]
@LincCodes 

Sorry for late reply.

Is this still happened?

If any troubles or updates, feel free to reopen the issue 🙏

**Comment by TimotiusAnrez** [comment]
I use quick fix that I have mentioned before, and it works like a charm. 

Tho I cannot says for others...
