### ISSUE TITLE
Cannot build electron packages

### ISSUE THREAD

**Issue by kaaax0815** [saltyshiomix/nextron#178]
Windows: 20H2 19042.985
Node: v16.1.0
Yarn: 1.22.10
Error Log
```Export successful. Files written to D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\app
[nextron] Building main process
[nextron] Packaging - please wait a moment
  • electron-builder  version=22.10.5 os=10.0.19042
  • loaded configuration  file=D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\electron-builder.yml
  • writing effective config  file=dist\builder-effective-config.yaml
  • packaging       platform=win32 arch=ia32 electron=12.0.7 appOutDir=dist\win-ia32-unpacked
  • Unpacking electron zip  zipPath=undefined
  ⨯ editions-autoloader-none-broadened: Unable to determine a suitable edition, even after broadening.  stackTrace=
                                                                                                          Error: editions-autoloader-none-broadened: Unable to determine a suitable edition, even after broadening.
                                                                                                              at new Errlop (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\errlop\edition-es5\index.js:61:18)
                                                                                                              at Object.errtion (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\editions\edition-es5\util.js:23:14)
                                                                                                              at determineEdition (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\editions\edition-es5\index.js:317:21)
                                                                                                              at solicitEdition (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\editions\edition-es5\index.js:350:16)
                                                                                                              at Object.requirePackage (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\editions\edition-es5\index.js:364:9)
                                                                                                              at Object.<anonymous> (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\istextorbinary\index.cjs:4:38)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1109:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
                                                                                                              at Module.load (node:internal/modules/cjs/loader:989:32)
                                                                                                              at Function.Module._load (node:internal/modules/cjs/loader:829:14)
                                                                                                              at Module.require (node:internal/modules/cjs/loader:1013:19)
                                                                                                              at require (node:internal/modules/cjs/helpers:93:18)   
                                                                                                              at Object.<anonymous> (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\app-builder-lib\electron-osx-sign\util.js:135:22)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1109:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
                                                                                                              at Module.load (node:internal/modules/cjs/loader:989:32)
                                                                                                          ↳ Error: editions-autoloader-none-suitable: Unable to determine a suitable edition, as none were suitable.
                                                                                                              at new Errlop (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\errlop\edition-es5\index.js:61:18)
                                                                                                              at Object.errtion (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\editions\edition-es5\util.js:23:14)
                                                                                                              at determineEdition (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\editions\edition-es5\index.js:327:19)
                                                                                                              at determineEdition (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\editions\edition-es5\index.js:312:12)
                                                                                                              at solicitEdition (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\editions\edition-es5\index.js:350:16)
                                                                                                              at Object.requirePackage (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\editions\edition-es5\index.js:364:9)
                                                                                                              at Object.<anonymous> (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\istextorbinary\index.cjs:4:38)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1109:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
                                                                                                              at Module.load (node:internal/modules/cjs/loader:989:32)
                                                                                                              at Function.Module._load (node:internal/modules/cjs/loader:829:14)
                                                                                                              at Module.require (node:internal/modules/cjs/loader:1013:19)
                                                                                                              at require (node:internal/modules/cjs/helpers:93:18)   
                                                                                                              at Object.<anonymous> (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\app-builder-lib\electron-osx-sign\util.js:135:22)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1109:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
                                                                                                          ↳ Error: editions-autoloader-edition-incompatible: editions-autoloader-edition-incompatible: The edition [TypeScript source code made to be compatible with Deno] is not compatible with this environment.
                                                                                                              at new Errlop (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\errlop\edition-es5\index.js:61:18)
                                                                                                              at Object.errtion (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\editions\edition-es5\util.js:23:14)
                                                                                                              at determineEdition (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\editions\edition-es5\index.js:301:25)
                                                                                                              at determineEdition (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\editions\edition-es5\index.js:312:12)
                                                                                                              at solicitEdition (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\editions\edition-es5\index.js:350:16)
                                                                                                              at Object.requirePackage (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\editions\edition-es5\index.js:364:9)
                                                                                                              at Object.<anonymous> (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\istextorbinary\index.cjs:4:38)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1109:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
                                                                                                              at Module.load (node:internal/modules/cjs/loader:989:32)
                                                                                                              at Function.Module._load (node:internal/modules/cjs/loader:829:14)
                                                                                                              at Module.require (node:internal/modules/cjs/loader:1013:19)
                                                                                                              at require (node:internal/modules/cjs/helpers:93:18)   
                                                                                                              at Object.<anonymous> (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\app-builder-lib\electron-osx-sign\util.js:135:22)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1109:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
                                                                                                          ↳ Error: editions-autoloader-edition-incompatible: editions-autoloader-edition-incompatible: The edition [TypeScript compiled against ES2019 for Node.js 12 || 14 || 15 with Import for modules] is not compatible with this environment.
                                                                                                              at new Errlop (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\errlop\edition-es5\index.js:61:18)
                                                                                                              at Object.errtion (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\editions\edition-es5\util.js:23:14)
                                                                                                              at determineEdition (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\editions\edition-es5\index.js:301:25)
                                                                                                              at determineEdition (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\editions\edition-es5\index.js:312:12)
                                                                                                              at solicitEdition (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\editions\edition-es5\index.js:350:16)
                                                                                                              at Object.requirePackage (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\editions\edition-es5\index.js:364:9)
                                                                                                              at Object.<anonymous> (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\istextorbinary\index.cjs:4:38)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1109:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
                                                                                                              at Module.load (node:internal/modules/cjs/loader:989:32)
                                                                                                              at Function.Module._load (node:internal/modules/cjs/loader:829:14)
                                                                                                              at Module.require (node:internal/modules/cjs/loader:1013:19)
                                                                                                              at require (node:internal/modules/cjs/helpers:93:18)   
                                                                                                              at Object.<anonymous> (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\app-builder-lib\electron-osx-sign\util.js:135:22)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1109:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
                                                                                                          ↳ Error: editions-autoloader-edition-incompatible: editions-autoloader-edition-incompatible: The edition [TypeScript compiled against ES2019 for Node.js 10 || 12 || 14 || 15 with Require for modules] is not compatible with this environment.
                                                                                                              at new Errlop (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\errlop\edition-es5\index.js:61:18)
                                                                                                              at Object.errtion (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\editions\edition-es5\util.js:23:14)
                                                                                                              at determineEdition (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\editions\edition-es5\index.js:301:25)
                                                                                                              at determineEdition (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\editions\edition-es5\index.js:312:12)
                                                                                                              at solicitEdition (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\editions\edition-es5\index.js:350:16)
                                                                                                              at Object.requirePackage (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\editions\edition-es5\index.js:364:9)
                                                                                                              at Object.<anonymous> (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\istextorbinary\index.cjs:4:38)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1109:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
                                                                                                              at Module.load (node:internal/modules/cjs/loader:989:32)
                                                                                                              at Function.Module._load (node:internal/modules/cjs/loader:829:14)
                                                                                                              at Module.require (node:internal/modules/cjs/loader:1013:19)
                                                                                                              at require (node:internal/modules/cjs/helpers:93:18)   
                                                                                                              at Object.<anonymous> (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\app-builder-lib\electron-osx-sign\util.js:135:22)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1109:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
                                                                                                          ↳ Error: editions-autoloader-edition-incompatible: editions-autoloader-edition-incompatible: The edition [TypeScript compiled against ESNext for Node.js 14 || 15 with Require for modules] is not compatible with this environment.
                                                                                                              at new Errlop (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\errlop\edition-es5\index.js:61:18)
                                                                                                              at Object.errtion (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\editions\edition-es5\util.js:23:14)
                                                                                                              at determineEdition (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\editions\edition-es5\index.js:301:25)
                                                                                                              at determineEdition (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\editions\edition-es5\index.js:312:12)
                                                                                                              at solicitEdition (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\editions\edition-es5\index.js:350:16)
                                                                                                              at Object.requirePackage (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\editions\edition-es5\index.js:364:9)
                                                                                                              at Object.<anonymous> (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\istextorbinary\index.cjs:4:38)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1109:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
                                                                                                              at Module.load (node:internal/modules/cjs/loader:989:32)
                                                                                                              at Function.Module._load (node:internal/modules/cjs/loader:829:14)
                                                                                                              at Module.require (node:internal/modules/cjs/loader:1013:19)
                                                                                                              at require (node:internal/modules/cjs/helpers:93:18)   
                                                                                                              at Object.<anonymous> (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\app-builder-lib\electron-osx-sign\util.js:135:22)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1109:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
                                                                                                          ↳ Error: editions-autoloader-edition-incompatible: editions-autoloader-edition-incompatible: The edition [TypeScript compiled against ES2019 for web browsers with Import for modules] is not compatible with this environment. 
                                                                                                              at new Errlop (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\errlop\edition-es5\index.js:61:18)
                                                                                                              at Object.errtion (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\editions\edition-es5\util.js:23:14)
                                                                                                              at determineEdition (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\editions\edition-es5\index.js:301:25)
                                                                                                              at determineEdition (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\editions\edition-es5\index.js:312:12)
                                                                                                              at solicitEdition (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\editions\edition-es5\index.js:350:16)
                                                                                                              at Object.requirePackage (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\editions\edition-es5\index.js:364:9)
                                                                                                              at Object.<anonymous> (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\istextorbinary\index.cjs:4:38)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1109:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
                                                                                                              at Module.load (node:internal/modules/cjs/loader:989:32)
                                                                                                              at Function.Module._load (node:internal/modules/cjs/loader:829:14)
                                                                                                              at Module.require (node:internal/modules/cjs/loader:1013:19)
                                                                                                              at require (node:internal/modules/cjs/helpers:93:18)   
                                                                                                              at Object.<anonymous> (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\app-builder-lib\electron-osx-sign\util.js:135:22)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1109:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
                                                                                                          ↳ Error: editions-autoloader-edition-incompatible: The edition [TypeScript source code with Import for modules] is not compatible with this environment.
                                                                                                              at new Errlop (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\errlop\edition-es5\index.js:61:18)
                                                                                                              at Object.errtion (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\editions\edition-es5\util.js:23:14)
                                                                                                              at isCompatibleEdition (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\editions\edition-es5\index.js:252:19)
                                                                                                              at determineEdition (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\editions\edition-es5\index.js:287:4)
                                                                                                              at determineEdition (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\editions\edition-es5\index.js:312:12)
                                                                                                              at solicitEdition (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\editions\edition-es5\index.js:350:16)
                                                                                                              at Object.requirePackage (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\editions\edition-es5\index.js:364:9)
                                                                                                              at Object.<anonymous> (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\istextorbinary\index.cjs:4:38)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1109:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
                                                                                                              at Module.load (node:internal/modules/cjs/loader:989:32)
                                                                                                              at Function.Module._load (node:internal/modules/cjs/loader:829:14)
                                                                                                              at Module.require (node:internal/modules/cjs/loader:1013:19)
                                                                                                              at require (node:internal/modules/cjs/helpers:93:18)   
                                                                                                              at Object.<anonymous> (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\app-builder-lib\electron-osx-sign\util.js:135:22)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1109:14)
                                                                                                          ↳ Error: editions-autoloader-invalid-engines: The edition had no engines to compare against the environment
                                                                                                              at new Errlop (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\errlop\edition-es5\index.js:61:18)
                                                                                                              at Object.errtion (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\editions\edition-es5\util.js:23:14)
                                                                                                              at isCompatibleEngines (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\editions\edition-es5\index.js:183:19)
                                                                                                              at isCompatibleEdition (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\editions\edition-es5\index.js:250:10)
                                                                                                              at determineEdition (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\editions\edition-es5\index.js:287:4)
                                                                                                              at determineEdition (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\editions\edition-es5\index.js:312:12)
                                                                                                              at solicitEdition (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\editions\edition-es5\index.js:350:16)
                                                                                                              at Object.requirePackage (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\editions\edition-es5\index.js:364:9)
                                                                                                              at Object.<anonymous> (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\istextorbinary\index.cjs:4:38)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1109:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
                                                                                                              at Module.load (node:internal/modules/cjs/loader:989:32)
                                                                                                              at Function.Module._load (node:internal/modules/cjs/loader:829:14)
                                                                                                              at Module.require (node:internal/modules/cjs/loader:1013:19)
                                                                                                              at require (node:internal/modules/cjs/helpers:93:18)   
                                                                                                              at Object.<anonymous> (D:\Bernd\BerndPC\Documents\Github\Typescript\electron-test\node_modules\app-builder-lib\electron-osx-sign\util.js:135:22)


Cannot build electron packages:
Error: Command failed with exit code 1: electron-builder --win --ia32```

**Comment by kaaax0815** [comment]
Fixed by settings `electron-builder` to `22.9.1`
