### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by markolofsen** [saltyshiomix/nextron#20]
```
$ yarn dev
yarn run v1.7.0
$ node build/nextron.js
module.js:545
    throw err;
    ^

Error: Cannot find module '****nextron/examples/with-typescript-material-ui/build/nextron.js'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3
```

**Comment by saltyshiomix** [comment]
Hi @markolofsen !
Thank you for your reporting the issue.

What is the version of nextron?
I tested it both on Windows and Mac, but I found no errors, sorry.

**Comment by markolofsen** [comment]
MacOS Sierra
```
$ nextron --version
nextron v4.0.1
```

**Comment by saltyshiomix** [comment]
@markolofsen 
Thank you very much for your information.
I'll investigate it.

**Comment by saltyshiomix** [comment]
@markolofsen 

I got it.
Because `nextron` is an app generator, so please be careful how to use.

Do not `yarn && yarn dev` under the `examples/with-typescript-material-ui` directly.
Correct usage is written in `README.md`.

https://github.com/saltyshiomix/nextron/blob/master/examples/with-typescript-material-ui/README.md

## Usage

### Create an App

```bash
# with `nextron` (after `npm install --global nextron@latest`)
$ nextron init my-app --template with-typescript-material-ui

# with npx
$ npx create-nextron-app my-app --example with-typescript-material-ui

# with yarn
$ yarn create nextron-app my-app --example with-typescript-material-ui
```

### Use it

```bash
$ cd my-app

# Install dependencies
$ yarn (or `npm install`)

# Run development mode
$ yarn dev (or `npm run dev`)

# Build packages
$ yarn build (or `npm run build`)
```

**Comment by markolofsen** [comment]
Sorry, thanks)
