### ISSUE TITLE
Standard _error.js - Error: The default export is not a React Component in page: "/_error"

### ISSUE THREAD

**Issue by michaelmika** [saltyshiomix/nextron#234]
I wanted to upgrade form nextJS 10 to 11 and nextron 7. This upgrade also changed the webpack version from 4 to 5 internally.

After the upgrade, I get this error when running dev:

```
Error: The default export is not a React Component in page: "/_error"
    at Object.renderToHTML (./node_modules/next/dist/server/render.js:220:19)
    at doRender (./node_modules/next/dist/server/next-server.js:1149:57)
    at ./node_modules/next/dist/server/next-server.js:1241:34
    at ./node_modules/next/dist/server/response-cache.js:64:42
    at ResponseCache.get (./node_modules/next/dist/server/response-cache.js:83:11)
    at DevServer.renderToResponseWithComponents (./node_modules/next/dist/server/next-server.js:1180:53)
    at DevServer.renderErrorToResponse (./node_modules/next/dist/server/next-server.js:1426:35)
    at async DevServer.renderToResponse (./node_modules/next/dist/server/next-server.js:1356:30)
    at async DevServer.pipe (./node_modules/next/dist/server/next-server.js:870:25)
    at async Object.fn (./node_modules/next/dist/server/next-server.js:674:21)

error - Error: The default export is not a React Component in page: "/home"
    at Object.renderToHTML (./node_modules/next/dist/server/render.js:220:19)
    at doRender (./node_modules/next/dist/server/next-server.js:1149:57)
    at ./node_modules/next/dist/server/next-server.js:1241:34
    at ./node_modules/next/dist/server/response-cache.js:64:42
    at ResponseCache.get (./node_modules/next/dist/server/response-cache.js:83:11)
    at DevServer.renderToResponseWithComponents (./node_modules/next/dist/server/next-server.js:1180:53)
    at DevServer.renderToResponse (./node_modules/next/dist/server/next-server.js:1311:39)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async DevServer.pipe (./node_modules/next/dist/server/next-server.js:870:25) {
  page: '/home'
}

```

I checked the _error.js File and it is pretty much the same as the one in the docs. I even deleted and renamed it, but the error persisted. I also tried to refactor it as a class component - also with no effect. It has nothing to do with the actual _error.js file. When I downgraded to nextjs 10 and nextron 6, it worked as expected. 

I also have a working web version without electron with the same page files (_error.js, home.js, ...) with nextjs 12 and webpack 5, so I guess it is a nextron issue and not a nextjs and webpack one.

**Comment by AlexisPiquet** [comment]
Hi, could you add you files as example? Only error stach is nott enougth to be understable.
