### ISSUE TITLE
Babel Error

### ISSUE THREAD

**Issue by Pedromdsn** [saltyshiomix/nextron#252]
Versions:
OS: Ubuntu 20.04
Node: 17.6.0
Nextron: 8.0.0 (tailwind with typescript template)

Note:
I didn't make any changes to the template.

```
ready - started server on 0.0.0.0:8888, url: http://localhost:8888
event - compiled client and server successfully in 538 ms (124 modules)
wait  - compiling /_error (client and server)...
event - compiled client and server successfully in 95 ms (125 modules)
Debugger listening on ws://127.0.0.1:9292/f6ce65c7-82dc-437e-a3cf-250f881d66b5
For help, see: https://nodejs.org/en/docs/inspector
App threw an error during load
Error: Cannot find module '@babel/runtime-corejs3/helpers/defineProperty'
    at webpackMissingModule (/home/pedro/www/native/teste/app/background.js:15:50)
    at Object../main/helpers/create-window.ts (/home/pedro/www/native/teste/app/background.js:15:170)
    at __webpack_require__ (/home/pedro/www/native/teste/app/background.js:192:41)
    at Object../main/helpers/index.ts (/home/pedro/www/native/teste/app/background.js:136:72)
    at __webpack_require__ (/home/pedro/www/native/teste/app/background.js:192:41)
    at /home/pedro/www/native/teste/app/background.js:251:66
    at /home/pedro/www/native/teste/app/background.js:284:3
    at Object.<anonymous> (/home/pedro/www/native/teste/app/background.js:287:12)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module '@babel/runtime-corejs3/helpers/defineProperty'
    at webpackMissingModule (/home/pedro/www/native/teste/app/background.js:15:50)
    at Object../main/helpers/create-window.ts (/home/pedro/www/native/teste/app/background.js:15:170)
    at __webpack_require__ (/home/pedro/www/native/teste/app/background.js:192:41)
    at Object../main/helpers/index.ts (/home/pedro/www/native/teste/app/background.js:136:72)
    at __webpack_require__ (/home/pedro/www/native/teste/app/background.js:192:41)
    at /home/pedro/www/native/teste/app/background.js:251:66
    at /home/pedro/www/native/teste/app/background.js:284:3
    at Object.<anonymous> (/home/pedro/www/native/teste/app/background.js:287:12)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    ```

**Comment by saltyshiomix** [comment]
@Pedromdsn 

Sorry for late reply.

Just rewrite tailwindcss example (v2 => v3), so please try it if you have some time 🙏

**Comment by moham96** [comment]
same problem here with basic typescript template

**Comment by moham96** [comment]
Fixed it by running `pnpm add @babel/runtime-corejs3`
