### ISSUE TITLE
"tsconfig paths" modules not found

### ISSUE THREAD

**Issue by Venipa** [saltyshiomix/nextron#270]
Node: v16.15.1
OS: Win 11 x64

Stacktrace:
```ts
App threw an error during load
Error: Cannot find module 'app/translations/app'
    at webpackMissingModule (E:\git\testapp-nextron\app\background.js:4266:50)
    at E:\git\testapp-nextron\app\background.js:4266:145
    at E:\git\testapp-nextron\app\background.js:4652:3
    at Object.<anonymous> (E:\git\testapp-nextron\app\background.js:4655:12)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at loadApplicationPackage (E:\git\testapp-nextron\node_modules\electron\dist\resources\default_app.asar\main.js:110:16)
```

tsconfig:
```json
{
  "compilerOptions": {
    "target": "ES2022",
    "module": "ESNext",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": false,
    "forceConsistentCasingInFileNames": true,
    "experimentalDecorators": true,
    "noEmit": true,
    "incremental": true,
    "esModuleInterop": true,
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "allowSyntheticDefaultImports": true,
    "importHelpers": true,
    "isolatedModules": true,
    "baseUrl": ".",
    "jsx": "preserve",
    "paths": {
      "/*": [
        "./*"
      ],
      "app/app/*": [
        "./main/app/*",
      ],
      "app/main/*": [
        "./main/*",
      ],
      "app/lib/*": [
        "./lib/*",
      ],
      "app/lib/": [
        "./lib"
      ],
      "app/renderer/*": [
        "./renderer/*"
      ],
      "app/translations/*": [
        "./translations/*",
      ]
    },
    "typeRoots": [
      "./node_modules/@types"
    ],
    "types": [
      "webpack-env"
    ]
  },
  "include": [
    "./nextron-shim.d.ts",
    "**/*.ts"
  ],
  "exclude": [
    "node_modules",
    "renderer/next.config.js",
    "app",
    "dist"
  ]
}
```

**Comment by Willem-Jaap** [comment]
Webpack can't resolve these paths by default, you need a plugin in order for this to work.
A plugin like [tsconfig-paths-webpack-plugin](https://github.com/dividab/tsconfig-paths-webpack-plugin)

You can take a look at the following issue for a working implementation: 
https://github.com/saltyshiomix/nextron/issues/235

**Comment by alexis-piquet** [comment]
@Venipa, Hey, I've already answered to a similar issue [here](https://github.com/saltyshiomix/nextron/issues/235), let me know if it works for you, and don't hesitate to close your issue if it solved.

**Comment by saltyshiomix** [comment]
@Venipa CC: @Willem-Jaap @alexis-piquet 

I just released nextron v8.12.0, which includes [tsconfig-paths-webpack-plugin](https://github.com/dividab/tsconfig-paths-webpack-plugin)!

If you have time, please try new examples:

ex.) `npx create-nextron-app test-app --example basic-lang-typescript`

**Comment by Willem-Jaap** [comment]
Cool, I'll check it out when I have the time!

**Comment by Willem-Jaap** [comment]
Next.js has built-in [support](https://nextjs.org/docs/app/building-your-application/configuring/absolute-imports-and-module-aliases) for absolute urls, its working there. However it does not seem to be working in the main dir.

Can you share an example for how to configure an alias for that directory?
