### ISSUE TITLE
Error when using local version of nextron on a local project

### ISSUE THREAD

**Issue by andirsun** [saltyshiomix/nextron#337]
I want to debug this library with one of my projects but I am facing an error.
I installed the library locally on my project
```
// Path to nextron library: /Users/andirsun/projects/streamline/nextron
// Installed the library
npm install -D /Users/andirsun/projects/streamline/nextron
```
After install the local version of nextron my project package.json looks like this:
```
...
    "nextron": "file:../nextron",
...
```
But after I try to run nextron command on my project I am facing this error:
```

> streamline@4.0.93 dev:desktop
> nextron

/Users/andirsun/projects/streamline/streamline-web {
  cwd: '/Users/andirsun/projects/streamline/streamline-web',
  stdio: 'inherit'
}
ready - started server on 0.0.0.0:8888, url: http://localhost:8888
info  - Loaded env from /Users/andirsun/projects/streamline/streamline-web/.env
[@sentry/nextjs] You are using edge functions or middleware. Please note that Sentry does not yet support error monitoring for these features.
Debugger listening on ws://127.0.0.1:9292/89f52975-d113-46e9-913d-f5d0144c5b67
For help, see: https://nodejs.org/en/docs/inspector
App threw an error during load
Error: Cannot find module '@babel/runtime-corejs3/helpers/defineProperty'
    at webpackMissingModule (/Users/andirsun/projects/streamline/streamline-web/app/background.js:238:50)
    at ./desktop/utils/createWindow.ts (/Users/andirsun/projects/streamline/streamline-web/app/background.js:238:170)
    at __webpack_require__ (/Users/andirsun/projects/streamline/streamline-web/app/background.js:832:41)
    at /Users/andirsun/projects/streamline/streamline-web/app/background.js:897:77
    at /Users/andirsun/projects/streamline/streamline-web/app/background.js:1054:3
    at Object.<anonymous> (/Users/andirsun/projects/streamline/streamline-web/app/background.js:1057:12)
    at Module._compile (node:internal/modules/cjs/loader:1141:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1196:10)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
event - compiled client and server successfully in 1834 ms (4030 modules)
```
How can I use the local version of nextron to test the library with my project?

**Comment by CMOISDEAD** [comment]
i solve that issue installing this package, `npm i @babel/runtime-corejs3`

**Comment by andirsun** [comment]
@CMOISDEAD that solved the issue but now I cant re-build the library because of this error.
```
> nextron
sh: /Users/andirsun/projects/streamline/streamline-mono/node_modules/.bin/nextron: Permission denied
```

**Comment by fyfirman** [comment]
I also experienced this issue. Shouldn't it include in `package.json` by default? @saltyshiomix

**Comment by saltyshiomix** [comment]
Hi @fyfirman , I agree with your opinion!

I'll add `@babel/runtime-corejs3` as a dependency later 🙇
