### ISSUE TITLE
Typescript + Less bug

### ISSUE THREAD

**Issue by dandevs** [saltyshiomix/nextron#4]
Using the with-typescript template...

### next.config.js
```js
const withTypeScript = require('@zeit/next-typescript')
const withLess = require('@zeit/next-less')
const { detectExportPathMap } = require('nextron')

module.exports = withTypeScript(withLess({
  webpack: (config) => {
    config.target = 'electron-renderer'
    return config
  },
  
  exportPathMap: detectExportPathMap
}))
```

```
yarn run v1.7.0$ nextronDefining routes from exportPathMap(node:9180) UnhandledPromiseRejectionWarning: Error: Chunk.entrypoints: Use Chunks.addGroup instead    at Chunk.set (C:\Users\Dan\Desktop\test\wit-ts\node_modules\webpack\lib\Chunk.js:829:9)    at C:\Users\Dan\Desktop\test\wit-ts\node_modules\extract-text-webpack-plugin\dist\index.js:176:40
    at Array.forEach (<anonymous>)
    at Compilation.<anonymous> (C:\Users\Dan\Desktop\test\wit-ts\node_modules\extract-text-webpack-plugin\dist\index.js:171:18)    at Compilation.applyPluginsAsyncSeries (C:\Users\Dan\Desktop\test\wit-ts\node_modules\tapable\lib\Tapable.js:206:13)
    at Compilation.seal (C:\Users\Dan\Desktop\test\wit-ts\node_modules\next\node_modules\webpack\lib\Compilation.js:605:8)
    at applyPluginsParallel.err (C:\Users\Dan\Desktop\test\wit-ts\node_modules\next\node_modules\webpack\lib\Compiler.js:504:17)
    at C:\Users\Dan\Desktop\test\wit-ts\node_modules\tapable\lib\Tapable.js:289:11
    at Promise.all.then (C:\Users\Dan\Desktop\test\wit-ts\node_modules\next\node_modules\webpack\lib\DynamicEntryPlugin.js:45:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:9180) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9180) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:9180) UnhandledPromiseRejectionWarning: Error: Chunk.entrypoints: Use Chunks.addGroup instead
    at Chunk.set (C:\Users\Dan\Desktop\test\wit-ts\node_modules\webpack\lib\Chunk.js:829:9)
    at C:\Users\Dan\Desktop\test\wit-ts\node_modules\extract-text-webpack-plugin\dist\index.js:176:40
    at Array.forEach (<anonymous>)
    at Compilation.<anonymous> (C:\Users\Dan\Desktop\test\wit-ts\node_modules\extract-text-webpack-plugin\dist\index.js:171:18)
    at Compilation.applyPluginsAsyncSeries (C:\Users\Dan\Desktop\test\wit-ts\node_modules\tapable\lib\Tapable.js:206:13)
    at Compilation.seal (C:\Users\Dan\Desktop\test\wit-ts\node_modules\next\node_modules\webpack\lib\Compilation.js:605:8)
    at applyPluginsParallel.err (C:\Users\Dan\Desktop\test\wit-ts\node_modules\next\node_modules\webpack\lib\Compiler.js:504:17)
    at C:\Users\Dan\Desktop\test\wit-ts\node_modules\tapable\lib\Tapable.js:289:11
    at Promise.all.then (C:\Users\Dan\Desktop\test\wit-ts\node_modules\next\node_modules\webpack\lib\DynamicEntryPlugin.js:45:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:9180) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
Done in 5.05s.
PS C:\Users\Dan\Desktop\test\wit-ts>
```

**Comment by saltyshiomix** [comment]
Thank you for your reporting a bug!
This is caused by difference between main process webpack version(v4) and renderer process one(v3 by next.js).

To fix this, I downgrade webpack to v3(`webpack@3.10.0` same as `next.js@6.1.1` internally).

I hope you'll enjoy nextron with instructions below:

```bash
# update nextron
$ npm install --global nextron@latest

# try 'examples/with-typescript-less'
$ nextron init test-app --template with-typescript-less
```
