### ISSUE TITLE
with-javascript-ant-design won't build with next

### ISSUE THREAD

**Issue by boneskull** [saltyshiomix/nextron#40]
Running `next build renderer` within a project generated with `nextron init --example with-javascript-ant-design` results in this:

```
Creating an optimized production build ...

> Using external babel configuration
> Location: "/Users/boneskull/projects/nextron-test/renderer/.babelrc"
Compiled successfully.

> Build error occurred
/Users/boneskull/projects/nextron-test/node_modules/antd/lib/style/index.css:7
body {
     ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:720:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/boneskull/projects/nextron-test/node_modules/antd/lib/button/style/css.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32) {
  type: 'SyntaxError',
  '$error': '$error'
}
```

(Running `nextron build` is somewhat problematic, because it allows `next build` to fail silently--I had to do this to figure out what actually happened)

**Comment by saltyshiomix** [comment]
@boneskull 

Thank you for your reporting the bug 🙏 

Fixed and released `nextron@5.2.0` 👍 

Could you try `with-javascript-ant-design` example again?

**Comment by roarbb** [comment]
I'm affraid it's still not working. Created new nextron app and tried to build it without any code changes.

```
npx create-nextron-app my-app --example with-javascript-ant-design
cd my-app
yarn && yarn build
```
then
```
Export successful
[nextron] Building main process


 ERROR  Failed to compile with 1 errors                                                             8:47:02 PM

 error

Entry module not found: Error: Can't resolve 'babel-loader' in '/Users/roarbb/Code/my-app'

[nextron] Packaging - please wait a moment
  • electron-builder  version=21.1.1 os=18.6.0
  • loaded configuration  file=/Users/roarbb/Code/my-app/electron-builder.yml
  • writing effective config  file=dist/builder-effective-config.yaml
  • packaging       platform=darwin arch=x64 electron=5.0.7 appOutDir=dist/mac
  ⨯ Application entry file "app/background.js" in the "/Users/roarbb/Code/my-app/dist/mac/My Nextron App.app/Contents/Resources/app.asar" does not exist. Seems like a wrong configuration.  stackTrace=
                                                                                                                                                                                               Error: Application entry file "app/background.js" in the "/Users/roarbb/Code/my-app/dist/mac/My Nextron App.app/Contents/Resources/app.asar" does not exist. Seems like a wrong configuration.
                                                                                                                                                                                                   at error (/Users/roarbb/Code/my-app/node_modules/app-builder-lib/src/asar/asarFileChecker.ts:7:12)
                                                                                                                                                                                                   at checkFileInArchive (/Users/roarbb/Code/my-app/node_modules/app-builder-lib/src/asar/asarFileChecker.ts:33:11)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by saltyshiomix** [comment]
@roarbb 

Thank you so much for your reporting bugs 💯

**Comment by saltyshiomix** [comment]
Dear @boneskull and @roarbb 

Finally fixed the bugs, and a little renewal with the example:

![](https://i.imgur.com/NrkTPe9.png)

I tested in 3 ways:

```bash
# with nextron
$ npm i -g nextron@latest
$ npm init test-app --example with-javascript-ant-design

# with npx
$ npx create-nextron-app test-app --example with-javascript-ant-design

# with yarn
$ yarn create nextron-app test-app --example with-javascript-ant-design
```

Fixed the issue with `nextron@5.3.0`, and update dependencies with `nextron@5.3.1` :)

**Comment by saltyshiomix** [comment]
@boneskull 

If fixed, I'll close the issue this weekend :)

**Comment by boneskull** [comment]
:+1: Fails with a code signing error now (mac), which is expected.

**Comment by boneskull** [comment]
@saltyshiomix Thank you for being so polite and helpful in your issues and PRs.  You're doing a great job

**Comment by saltyshiomix** [comment]
@boneskull 

No problem!
(This is my mistake and I owe it :)

Anyway, thank you for trying nextron 🙏

**Comment by r0b1n1sl4m** [comment]
I've having this same issue with material ui, anyone knows the fix for it?
