### ISSUE TITLE
create-nextron-app does not work behind a proxy

### ISSUE THREAD

**Issue by raffaeleguidi** [saltyshiomix/nextron#435]
Even though http_proxy variables are properly set the proxy is ignored and the cli returns an unmanaged error (see below). I'm using windows 10 and Node.js v18.13.0

```
C:\Users\me\develop>npx create-nextron-app nextron-app --example with-tailwindcss
\ Validating existence...RequestError [HttpError]: fetch failed
    at C:\Users\me\AppData\Local\npm-cache\_npx\b53a4342db57cff4\node_modules\@octokit\request\dist-node\index.js:146:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async validateExistence (C:\Users\585738\AppData\Local\npm-cache\_npx\b53a4342db57cff4\node_modules\create-nextron-app\index.js:71:3)
    at async createNextronApp (C:\Users\me\AppData\Local\npm-cache\_npx\b53a4342db57cff4\node_modules\create-nextron-app\index.js:52:5) {
  status: 500,
  request: {
    method: 'GET',
    url: 'https://api.github.com/repos/saltyshiomix/nextron/contents/examples%2Fwith-tailwindcss%2Fpackage.json?ref=main',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-rest.js/19.0.5 octokit-core.js/4.2.4 Node.js/18.13.0 (win32; x64)'
    },
    request: { hook: [Function: bound bound register] }
  }
}
× Validating existence...

Error! Not found: with-tailwindcss
```

**Comment by raffaeleguidi** [comment]
Also I cannot find anywhere in the docs a way to use the proxy

**Comment by bm777** [comment]
Did you try ? @raffaeleguidi 

```bash
npx create-nextron-app nextron-app --example https://github.com/saltyshiomix/nextron/tree/main/examples/with-tailwindcss
```

**Comment by Harshalyadav** [comment]
You can try using Node.js version 16.17.0 or any 16 version
