### ISSUE TITLE
Nextron js is completely broken - Everything does not seems to work anymore

### ISSUE THREAD

**Issue by RocksWon** [saltyshiomix/nextron#477]
I installed the ant-design nextron package with yarn and it has not been successful for me for the past 3 days. Each time I launch the application it throws this error. 

import _extends from "@babel/runtime/helpers/esm/extends".
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1281:20)
    at Module._compile (node:internal/modules/cjs/loader:1321:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at mod.require (path\node_modules\next\dist\server\require-hook.js:65:28)
    at require (node:internal/modules/helpers:179:18)
    at @ant-design/icons/es/icons/DownOutlined (path\renderer\.next\server\pages\home.js:182:18)
    at __webpack_require__ (path\renderer\.next\server\webpack-runtime.js:33:42)
    at eval (webpack-internal:///../node_modules/antd/es/table/hooks/useSelection.js:12:97)
    at ../node_modules/antd/es/table/hooks/useSelection.js (path\renderer\.next\server\vendor-chunks\antd.js:1846:1)
    at __webpack_require__ (path\renderer\.next\server\webpack-runtime.js:33:42)
    at eval (webpack-internal:///../node_modules/antd/es/table/Table.js:12:77)
    at __webpack_require__.a (path\renderer\.next\server\webpack-runtime.js:97:13) {
  page: '/home'
}

This error throws when I try to use the antd component.  I have tried everything for about 3 days now and working for me. At first nextron js was not like this but now everything is in a shamble. The crash rate is nearly 100%. In case anyone knows how to fix this issue kindly help me with it.

**Comment by RocksWon** [comment]
So, upon thorough research and investigation I found a solution to the problem. But the thing is I don't know if its temporal or permanent solution only God will tell along the way.

**Comment by AlejandroFNadal** [comment]
Hey, what was the solution @RocksWon ?

**Comment by AlejandroFNadal** [comment]
What worked for me was to convert the import to a require in my preload script, and also making sure all my scripts under main were Typescript based:
```
//import { contextBridge, ipcRenderer } from 'electron'
const { contextBridge, ipcRenderer } = require("electron");
```
